-d D:\Codes\VHDL\Gowin\VBC-1\impl\gwsynthesis\VBC-1.vg
-p GW1NZ-1-QFN48-6
-pn GW1NZ-LV1QN48C6/I5
-cst D:\Codes\VHDL\Gowin\VBC-1\src\VBC-1.cst
-cfg D:\Codes\VHDL\Gowin\VBC-1\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 10
-global_freq 50.000
